application_name: 'Hackpad Gmail Reader'

# Gmail
credentials_dir_name: '.credentials'
credentials_file_name: 'hackpad-gmail-reader.json'
client_secret_file_name: 'client_secret.json'
email_page_size: 10
gmail_query_string: 'label:hackpad-import label:unread'
oauth2_scopes:
  - 'https://www.googleapis.com/auth/gmail.modify'

# Download Directory
download_directory: ./attachments

# Where to queue Jobs
redis:
  url: redis://localhost:6379/9
  queue_name: hackpad_imports
  error_queue_name: hackpad_import_errors
