#
# Logging Configuration File
#

# Logging Configuration
version: 1

# Configure the log formatters
formatters:
    brief:
       format: "%(asctime)s - %(name)-15s - %(process)-5d - %(levelname)-6s - %(message)s"
    precise:
       format: "%(asctime)s - %(name)-15s - %(process)-5d - %(levelname)-6s - %(message)s"
    common-http-format:
       format: "%(message)s"


# Configure the logging handlers
handlers:
    console:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        formatter: brief
        level: DEBUG
    file:
        class : logging.handlers.RotatingFileHandler
        formatter: precise
        filename: hackpad-email-reader.log
        maxBytes: 1048576
        backupCount: 3
        level: DEBUG

# Root logger
root:
    handlers: [console]
    level: DEBUG


# Configure individual loggers
loggers:
    app:
        handlers: [file]


